version: 2.1

executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2021.07

jobs:
  publish-protobuf-files:
    executor: base-cimg-executor
    steps:
      - checkout
      - run:
          name: Publish protobuf to buf.build
          command: |
            echo "Will publish protobuf to buf.build"

  tag-github-repository:
    executor: base-cimg-executor
    parameters:
      repository:
        type: string
        description: Github repository to tag (organization/repository)
      deployment-key:
        type: string
        description: Deployment key to use when interacting with remote repository
      tag:
        type: string
        description: What git tag to use when tagging remote repository
    steps:
      - run:
          name: Checkout github repository
          command: |
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_$(echo "<< parameters.deployment-key >>" | tr -d ':')"
            export SSH_AUTH_SOCK=""
            git clone ssh://git@github.com/<< parameters.repository >> /home/circleci/project
      - run:
          name: Create release tag in the repository
          command: |
            cd /home/circleci/project
            git tag --annotate -m "Releasing version << parameters.tag >>" << parameters.tag >>
      - run:
          name: Push release tags to remote repository
          command: |
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_$(echo "<< parameters.deployment-key >>" | tr -d ':')"
            export SSH_AUTH_SOCK=""
            echo "git push origin --tags""

workflows:
  version: 2

  tag-aperture-blueprints:
    when: &job-when-clause
      matches: { value: << pipeline.git.tag >>, pattern: ^v.* }
    jobs:
      - tag-github-repository: &tag-github-repository
          # both this and workflow's when is needed
          filters:
            branches:
              ignore: /.+/
            tags:
              only: /^v.*/
          repository: fluxninja/aperture-blueprints
          tag: << pipeline.git.tag >>
          deployment-key: xx:yy

  tag-aperture-go-sdk:
    when: *job-when-clause
    jobs:
      - tag-github-repository:
          <<: *tag-github-repository
          repository: fluxninja/aperture-go
          deployment-key: yy:zz

  publish-protobuf-files:
    when: *job-when-clause
    jobs:
      - publish-protobuf-files
