apiVersion: fluxninja.com/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  etcd:
    endpoints: ["http://controller-etcd:2379"]
  prometheus:
    address: "http://controller-prometheus-server:80"
  config:
    otel:
      batch_prerollup:
        timeout: 2s
