apiVersion: v1
kind: Service
metadata:
  name: { { include "demoapp-go.fullname" . } }
  labels: { { - include "demoapp-go.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: srvhttp
      protocol: TCP
      name: http
  selector: { { - include "demoapp-go.selectorLabels" . | nindent 4 } }
